services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ollive-mongo:/data/db

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: mongodb://mongo:27017/ollive?retryWrites=true&w=majority
    depends_on:
      - mongo

volumes:
  ollive-mongo:
